### ISSUE TITLE
Return type of surge.Project.delete inconsistent with documentation

### ISSUE THREAD

**Issue by yichern** [surge-ai/surge-python#45]
As per the documentation, the return type of `delete` is a dictionary as such

```
{"success": "true"}
```

However, the SDK actually returns a dictionary as such

```
{"success": True}
```

Code to repliacate:

```python
import surge
project = surge.Project.create(name="test project")
status = project.delete()
type(status["success"])
>>> bool
```

**Comment by amauboussin** [comment]
We [updated the docs](https://app.surgehq.ai/docs/api#delete-a-project) to reflect the proper return values (`{"success": True}` for the Python SDK and `{"success": "true"}` for direct API usage). Thanks @yichern!
